framework:
    router:
        utf8: true
# authentication_token:
#     path: /authentication_token
#     methods: ['POST']
# api_platform:
#     swagger:
#          api_keys:
#              apiKey:
#                 name: Authorization
#                 type: header